name: Barista preview

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    container: designops/workspace-base:latest
    env:
      WORKSPACE_DIR: /dynatrace
    steps:
      - uses: actions/checkout@v2

      - name:
          Link the node_modules and the builders in the current working
          directory
        run: |
          cp -R "$WORKSPACE_DIR/dist" "$PWD/dist"
          ln -s "$WORKSPACE_DIR/node_modules" "$PWD/node_modules"
          ln -s "$WORKSPACE_DIR/package-lock.sha1" "$PWD/package-lock.sha1"

          ./.deployment/entrypoint.sh

      - name: Build Barista Design System
        run: |
          npm run ng run workspace:build
          npm run ng run barista-tools:build
          npm run ng run barista-tools:execute
          npm run ng run barista-design-system:static-pages:production

      - name: Vercel Deployment
        id: vercel-action
        uses: amondnet/vercel-action@v19.0.1+4
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-args:
            '--scope dynatrace-oss --confirm
            ./dist/apps/barista-design-system/browser'
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}

      - name: Generating Lighthouse Report
        uses: jakejarvis/lighthouse-action@master
        with:
          url: ${{ steps.vercel-action.outputs.preview-url }}

      - name: Save Lighthouse Audit
        uses: actions/upload-artifact@master
        with:
          name: barista-audit
          path: './report'
